# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# GitHub recommends pinning actions to a commit SHA.
# To get a newer version, you will need to update the SHA.
# You can also reference a tag or branch, but the action may change without warning.

name: Deploy to Amazon ECS

on:
  push:
    branches:
      - staging
  workflow_dispatch:

env:
  AWS_REGION: ap-southeast-1 # set this to your preferred AWS region, e.g. us-west-1
  ECR_REPOSITORY: projectcicd # set this to your Amazon ECR repository name
  ECS_SERVICE: ECSpeojectcicdservice # set this to your Amazon ECS service name
  ECS_CLUSTER: ProjectCicd # set this to your Amazon ECS cluster name
  ECS_TASK_DEFINITION:
    projectcicdtask # set this to the path to your Amazon ECS task definition  projectcicdtask
    # file, e.g. .aws/task-definition.json
  CONTAINER_NAME:
    projectcicdapp # set this to the name of the container in the   projectcicdapp
    # containerDefinitions section of your task definition

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '14.x'
      - name: Install dependencies
          run: yarn install

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy Next.js app
        run: npx serverless
